# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-07-19 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20161006_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opus',
            name='subtitle',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='progress',
            name='status',
            field=models.CharField(choices=[('active', (('inprogress', '进行中'), ('follow', '追剧中'), ('todo', '待阅读'), ('error', '出错'))), ('archive', (('done', '已完成'), ('giveup', '冻结中')))], max_length=50),
        ),
        migrations.AlterField(
            model_name='userexp',
            name='category',
            field=models.CharField(choices=[('progress', '进度活跃度'), ('user', '用户活跃度'), ('chat', '消息活跃度'), ('error', '错误类别')], max_length=255),
        ),
    ]
