# Generated by Django 2.0.1 on 2018-01-29 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_auto_20180129_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opus',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
    ]
