# Generated by Django 2.0.1 on 2018-01-30 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_auto_20180129_1311'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='status',
            field=models.CharField(choices=[('active', (('inprogress', '进行中'), ('follow', '追剧中'), ('todo', '待阅读'), ('error', '出错'))), ('archive', (('done', '已完成'), ('deactivated', '冻结中')))], max_length=50),
        ),
    ]
