# Generated by Django 2.0.1 on 2018-08-28 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0033_auto_20180130_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='comment',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='progress',
            name='name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='progress',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
