# Generated by Django 2.0.1 on 2018-08-28 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0035_auto_20180828_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='progress',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
