# Generated by Django 3.0.7 on 2020-10-17 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0036_auto_20180828_2315'),
    ]

    operations = [
        migrations.AddField(
            model_name='progress',
            name='underway',
            field=models.BooleanField(default=False),
        ),
    ]
